services:
    afsy_blackjack.start_game.command_handler:
        class: Afsy\App\GameEngineService
        arguments: [@afsy_blackjack.dealer, @cqrs.event_source.repository]
        tags:
            - { name: lite_cqrs.command_handler }
