services:
    afsy_blackjack.game_view.listener:
        class: Afsy\Blackjack\Domain\Listener\GameViewListener
        arguments: [@afsy_blackjack.game_view.repository.orm]
        tags:
            - { name: lite_cqrs.event_handler }
